### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by Nuri-benbarka**
This is an addition to the README to help users who will encounter this problem

### CODE REVIEW

**Comment by erksch** [comment]
Awesome thank you! Just two style things: Please add a newline between the two sentences and add a ':' at the end. (Newline is with two spaces at the end of a line).

**Comment by erksch** [comment]
Thanks!

**Comment by Nuri-benbarka** [comment]
Made the requested changes

**Comment by Nuri-benbarka** [comment]
your welcome :)

**Pull request merged**
